### ISSUE TITLE
[Blocker] - Marvin App - an error occurs when the user deletes the workspaces and root execution folder in the tree

### ISSUE THREAD

**Issue by ralucabrie** [ascentcore/marvin#153]
Preconditions: Make sure you have some workspaces and some execution flows

Steps to Reproduce:
1. Start Marvin Frontend
2. Start Marvin
3. in UI - Go to Workspaces and delete all the existing workspaces
4. Go to Execution Flows - delete the root folder from the execution tree.

Actual Results:
An error is displayed in UI.
If you close the error, nothing is displayed in the Electron app

<img width="910" alt="image" src="https://user-images.githubusercontent.com/15820565/230297681-ec263d56-15b7-41f4-8b3d-25ace7f2ddbc.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/15820565/230298140-98ea0818-fc2c-49e1-8151-323148501362.png">

Expected Results:
No error is displayed.

**Comment by cstefanache** [comment]
fixed on branch: sequences
