### ISSUE TITLE
Investigate flow discovery

### ISSUE THREAD

**Issue by cstefanache** [ascentcore/marvin#2]
We had an idea in the past to build an automation framework that can use the same functionality as a web scraper to build a `sitemap`/`flowmap`

1. For a given url `hxxp(s)://...` it will navigate to that page and will identify actionable components (form components, buttons, etc.)
2. The user will be prompted with the findings. For the login screen the "scraper" will identify the `username`, `password` form components, buttons and links to: `forgot password` and `register` screens. 
3. The user will have the option to give values for that username/password fields and this information will go into the descriptor alongside with the values for the username and password.
4. The user can chose to "autodiscover" the rest of the flow using the given data values

The developer can chose to add different values for the username and password so it can describe multiple flows
With each pair of data the user will fork the flow testing possibilities

**Comment by claudiu197** [comment]
For the scraping part, are we going to use a dedicated tool? e.g. scrapy - https://docs.scrapy.org/en/latest/
