### ISSUE TITLE
Define descriptor format

### ISSUE THREAD

**Issue by cstefanache** [ascentcore/marvin#3]
We need to investigate a clean way to define the descriptor that will be used by the scraper and the test generators.

As a follow-up of the story #2 I am thinking that the descriptor can contain a section where we can define the `actionables`. Because most CSS Frameworks and UI Component libraries do not use the classic html components: `button`, `input type="xxx"` then we can add a set of **query selector templates** (something like `.btn`) that the framework will look into it.

(this story is WIP)

**Comment by cstefanache** [comment]
The same descriptor can use `verifiables` identifiers that will be used to generate the `assertions`. E.g. a verifiable can be: `.error-message`. And when the scraper will identify this verifiable in the page it will automatically generate an assertion.

**Comment by claudiu197** [comment]
From what I understood so far on the scrapy side, we might be able to identify elements by their defined action triggers (e.g. on click -> opens /account page: get the href link from the button and build an assertion with the landing page url)
