### ISSUE TITLE
Introduce functions in value setting

### ISSUE THREAD

**Issue by cstefanache** [ascentcore/marvin#60]
Curently setting a property value is fixed to a single value. We need to have a dynamic way to define this

Current sample:
```
"fdc358f1-3837-4fbd-be96-0a576ee9c9f7": "Item 3"
```

We need to add a library of functions that can be used here:

Sample:
```
"fdc358f1-3837-4fbd-be96-0a576ee9c9f7": "Item - {randomInt(1000, 65536)}"
```

- `randomInt(min, max)` - generates a random number between min and max
- `random(min, max)` - generates a  random float between min and max (if min and max are not specified) it will generate between 0 and 1
- `store(varName)` - injects the value loaded from store

**Comment by cstefanache** [comment]
Having the property store available on runner. The property will become the executing and interpreting context for everything that needs to be replaced as a value.

Given the following example:

```
store = {
   "property1" : 123,
   "property2": "stringProp"
}
```

when type is `fill` is found the expression needs to be interpreted instead of just setting the value as such:

```
"fdc358f1-3837-4fbd-be96-0a576ee9c9f7": "prop and ${property1}"
```

the actual value filled should be:
```
eval("with (store) `"+parameters[uid]+"`")
```
where `parameters[uid]` is the value in the placeholder.




To create a library of functions that can be used store can also hold default methods defined that can be used. e.g.
```
const store = {
   "func": {
        "random": () => Math.random()
        "randomInt": (min, max) => min + Math.floor( (max-min) * Math.random()) 
   }
}
```

so the user can define
```
"fdc358f1-3837-4fbd-be96-0a576ee9c9f7": "value-${func.randomInt(10,20)}"
```

**Comment by ralucabrie** [comment]
@cstefanache due to the fact that 'with' is forbidden in strict mode (and our app uses StrictMode) I used the eval() in a classic manner. 
For the part with library validation, I reported a different issue: https://github.com/ascentcore/marvin/issues/78

Here is a PR ready for review for "Introduce 'store' as a type to store locator content for later use" & "Introduce functions in value setting" issues:  https://github.com/ascentcore/marvin/pull/77

**Comment by cstefanache** [comment]
disable strict mode for now
