### ISSUE TITLE
Search for aliases in the page

### ISSUE THREAD

**Issue by cstefanache** [ascentcore/marvin#7]
After each `load` or `action` a new alias search will be performed to check if new components got shown or hidden.

an alias is defined as such
```
"aliases": {
   "button": { 
       "selectors": ["button", ".btn"]
   },
   "container":  {
       "selectors": [".paper", ".card"],
       "allow_grouping": true
}
```

if an alias allows grouping as property then a new search will be performed on that DOM element to see what subset of components is grouping

**Comment by ralucabrie** [comment]
this one is already implemented
