### ISSUE TITLE
Change the waiting for networkidle2 to be configurable

### ISSUE THREAD

**Issue by ralucabrie** [ascentcore/marvin#8]
**Problem observed**:
Trying to run the discovery for `https://app.gremlin.com/`, I observed the navigation to the page doesn't work and no result was generated. 

**Suggested solution**:
Change the  `await page.waitForNavigation({waitUntil: 'networkidle2'});` to be configurable.

**Comment by cstefanache** [comment]
Please test with ```await page.waitForNetworkIdle();``` might be the solution we are looking for

**Comment by cstefanache** [comment]
Solved using `page.waitForNetworkIdle()`

**Comment by ralucabrie** [comment]
We need to configure a default timeout for this. For some complex apps (eg Gremlin) this solution is not enough. I tried with  await page.waitForNetworkIdle({timeout: 5000}) and it worked.
